# Generated by Django 3.2.14 on 2023-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_health_main_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='prescription_img',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_pics'),
        ),
    ]
