# Generated by Django 3.2.14 on 2023-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_receta_prescription_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='prescription_img',
            field=models.ImageField(upload_to='recetas_pics'),
        ),
    ]
