# Generated by Django 3.2.14 on 2023-02-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_doctor_user'),
        ('health', '0004_alter_receta_prescription_img'),
    ]

    operations = [
    ]
