# Generated by Django 3.2.14 on 2023-02-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
